// <auto-generated />
using System;
using Bank_management__System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank_management__System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank_management__System.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountNumber"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpeingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountNumber");

                    b.HasIndex("BranchCode");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = 1000001,
                            AccountType = "Saving",
                            BranchCode = 101,
                            CurrentBalance = 50000.75m,
                            OpeingDate = new DateTime(2025, 11, 4, 17, 46, 4, 676, DateTimeKind.Local).AddTicks(1490)
                        },
                        new
                        {
                            AccountNumber = 1000002,
                            AccountType = "Current",
                            BranchCode = 101,
                            CurrentBalance = 125000.00m,
                            OpeingDate = new DateTime(2026, 2, 4, 17, 46, 4, 676, DateTimeKind.Local).AddTicks(1618)
                        },
                        new
                        {
                            AccountNumber = 1000003,
                            AccountType = "Saving",
                            BranchCode = 102,
                            CurrentBalance = 7500.50m,
                            OpeingDate = new DateTime(2026, 4, 4, 17, 46, 4, 676, DateTimeKind.Local).AddTicks(1632)
                        });
                });

            modelBuilder.Entity("Bank_management__System.Models.Branch", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Code = 101,
                            Address = "ElMamora",
                            ManagerId = 1,
                            Name = "Alex",
                            Phone = "0223456789"
                        },
                        new
                        {
                            Code = 102,
                            Address = "ElThrier",
                            ManagerId = 2,
                            Name = "Cairo",
                            Phone = "0345678901"
                        });
                });

            modelBuilder.Entity("Bank_management__System.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Bank_management__System.Models.CustomerAccount", b =>
                {
                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("OwnerShipStartDate")
                        .HasColumnType("date");

                    b.Property<string>("OwnerShipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountNumber", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAccount");
                });

            modelBuilder.Entity("Bank_management__System.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.hassan@bank.com",
                            FullName = "Ahmed Hassan",
                            HireDate = new DateOnly(2023, 5, 15),
                            PhoneNumber = "01012345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara.mohamed@bank.com",
                            FullName = "Sara Mohamed",
                            HireDate = new DateOnly(2024, 1, 10),
                            PhoneNumber = "01198765432"
                        });
                });

            modelBuilder.Entity("Bank_management__System.Models.Transaction", b =>
                {
                    b.Property<int>("TransactinNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactinNumber"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactinNumber");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Bank_management__System.Models.Account", b =>
                {
                    b.HasOne("Bank_management__System.Models.Branch", "Branch")
                        .WithMany("Accounts")
                        .HasForeignKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Bank_management__System.Models.Branch", b =>
                {
                    b.HasOne("Bank_management__System.Models.Manager", "Manager")
                        .WithOne("Branch")
                        .HasForeignKey("Bank_management__System.Models.Branch", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Bank_management__System.Models.CustomerAccount", b =>
                {
                    b.HasOne("Bank_management__System.Models.Account", "Accounts")
                        .WithMany("Customers")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerAccount_Account");

                    b.HasOne("Bank_management__System.Models.Customer", "Customers")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CustomerAccount_Customer");

                    b.Navigation("Accounts");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Bank_management__System.Models.Transaction", b =>
                {
                    b.HasOne("Bank_management__System.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Bank_management__System.Models.Account", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Bank_management__System.Models.Branch", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Bank_management__System.Models.Customer", b =>
                {
                    b.Navigation("CustomerAccounts");
                });

            modelBuilder.Entity("Bank_management__System.Models.Manager", b =>
                {
                    b.Navigation("Branch")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
